@startuml
'https://plantuml.com/activity-diagram-beta

start

if (Check if number <= 1?) then (true)
  :Return number;
else (false)
:prevPrev = 0;
:prev = 0;
:current = 1;
:i = 2;
    while (i <= number) is (true)
    :current = prevPrev + prev;
    :prevPrev = prev;
    :prev = current;
    :i++;
    endwhile
    :Return current;
  endif

stop

@enduml
